import { Router, type IRouter } from "express";
import healthRouter from "./health";
import waitlistRouter from "./waitlist";
import calendarRouter from "./calendar";
import authRouter from "./auth";
import userDataRouter from "./user-data";
import aiChatRouter from "./ai-chat";
import storageRouter from "./storage";
import brandingRouter from "./branding";
import brokerOnboardRouter from "./broker-onboard";
import adminRouter from "./admin";
import brokerRouter from "./broker";
import warrantiesRouter from "./warranties";
import documentsRouter from "./documents";
import smsRouter from "./sms";
import stripeRouter from "./stripe";
import stripeSeedRouter from "./stripe-seed";
import supportRouter from "./support";
import adminTestingRouter from "./admin-testing";
import feedbackRouter from "./feedback";

const router: IRouter = Router();

router.use(healthRouter);
router.use(waitlistRouter);
router.use(calendarRouter);
router.use(authRouter);
router.use(userDataRouter);
router.use(aiChatRouter);
router.use(storageRouter);
router.use(brandingRouter);
router.use(brokerOnboardRouter);
router.use(adminRouter);
router.use(brokerRouter);
router.use(warrantiesRouter);
router.use(documentsRouter);
router.use(smsRouter);
router.use(stripeRouter);
router.use(stripeSeedRouter);
router.use(supportRouter);
router.use(adminTestingRouter);
router.use(feedbackRouter);

export default router;
